### ISSUE TITLE
Unmet peer dependency Babel Loader

### ISSUE THREAD

**Issue by rwrobe** [DekodeInteraktiv/heisenberg#32]
In building Heisenberg for the first time inside planck, this error pops up:

```
Failed to compile.

Module not found: Error: Can't resolve 'babel-loader' in 'pathy mcpatherson'
```

Installing babel-loader independently in the theme fixes the error for now, but is obviously a bad solution. My suggestion is to upgrade the dependencies and will submit a PR.

**Comment by walbo** [comment]
Think this should be fixed in v0.3.0
